package com.twosigma.documentation.parser.sphinx.xml;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;

/**
 * @author mykola
 */
public class DocTreeDomXmlParser {
    public static void main(String[] args) throws Exception {
        DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
        DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
        Document doc = dBuilder.parse(new ByteArrayInputStream(xml().getBytes(StandardCharsets.UTF_8.name())));

        doc.getDocumentElement().normalize();

        NodeList entries = doc.getElementsByTagName("*");
        for (int i=0; i<entries.getLength(); i++) {
            Element element = (Element) entries.item(i);

            System.out.println(element.getTagName());
        }
    }

    private static String xml() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<!DOCTYPE document PUBLIC \"+//IDN docutils.sourceforge.net//DTD Docutils Generic//EN//XML\" \"http://docutils.sourceforge.net/docs/ref/docutils.dtd\">\n" +
                "<!-- Generated by Docutils 0.14 -->\n" +
                "<document source=\"/Users/mykola/work/sphinx-doc-test/index.rst\">\n" +
                "    <comment xml:space=\"preserve\">test-doc documentation master file, created by\n" +
                "sphinx-quickstart on Fri Sep 15 21:29:16 2017.\n" +
                "You can adapt this file completely to your liking, but it should at least\n" +
                "contain the root `toctree` directive.</comment>\n" +
                "    <section ids=\"welcome-to-test-doc-s-documentation\" names=\"welcome\\ to\\ test-doc's\\ documentation!\">\n" +
                "        <title>Welcome to test-doc’s documentation!</title>\n" +
                "        <compound classes=\"toctree-wrapper\">\n" +
                "        </compound>\n" +
                "    </section>\n" +
                "    <section ids=\"indices-and-tables\" names=\"indices\\ and\\ tables\">\n" +
                "        <title>Indices and tables</title>\n" +
                "        <paragraph>Hello World for real</paragraph>\n" +
                "        <bullet_list bullet=\"*\">\n" +
                "            <list_item>\n" +
                "                <paragraph><reference internal=\"True\" refuri=\"genindex\"><inline classes=\"std std-ref\">Index</inline></reference></paragraph>\n" +
                "            </list_item>\n" +
                "            <list_item>\n" +
                "                <paragraph><reference internal=\"True\" refuri=\"py-modindex\"><inline classes=\"std std-ref\">Module Index</inline></reference></paragraph>\n" +
                "            </list_item>\n" +
                "            <list_item>\n" +
                "                <paragraph><reference internal=\"True\" refuri=\"search\"><inline classes=\"std std-ref\">Search Page</inline></reference></paragraph>\n" +
                "            </list_item>\n" +
                "        </bullet_list>\n" +
                "        <section ids=\"sub\" names=\"sub\">\n" +
                "            <title>Sub</title>\n" +
                "        </section>\n" +
                "    </section>\n" +
                "</document>\n";
    }
}
