import React, {Component} from "react"
import GraphVizSvg from './graphviz/GraphVizSvg'

const testData = {
    "diagram": {
        "shapeSvgByStyleId": {},
        "isInvertedTextColorByStyleId": {},
        "svg": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"UTF-8\" standalone\u003d\"no\"?\u003e\n\u003c!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"\u003e\n\u003c!-- Generated by graphviz version 2.38.0 (20140413.2041)\n --\u003e\n\u003c!-- Title: Generated Pages: 1 --\u003e\n\u003csvg width\u003d\"242pt\" height\u003d\"109pt\"\n viewBox\u003d\"0.00 0.00 242.00 109.00\" xmlns\u003d\"http://www.w3.org/2000/svg\" xmlns:xlink\u003d\"http://www.w3.org/1999/xlink\"\u003e\n\u003cg id\u003d\"graph0\" class\u003d\"graph\" transform\u003d\"scale(1 1) rotate(0) translate(4 105)\"\u003e\n\u003ctitle\u003eGenerated\u003c/title\u003e\n\u003cpolygon fill\u003d\"white\" stroke\u003d\"none\" points\u003d\"-4,4 -4,-105 238,-105 238,4 -4,4\"/\u003e\n\u003c!-- n1 --\u003e\n\u003cg id\u003d\"node1\" class\u003d\"node\"\u003e\u003ctitle\u003en1\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"black\" points\u003d\"0,-0.5 0,-36.5 54,-36.5 54,-0.5 0,-0.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"27\" y\u003d\"-14.3\" font-family\u003d\"Times,serif\" font-size\u003d\"14.00\"\u003elabel 1\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n2 --\u003e\n\u003cg id\u003d\"node2\" class\u003d\"node\"\u003e\u003ctitle\u003en2\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"black\" points\u003d\"90,-64.5 90,-100.5 144,-100.5 144,-64.5 90,-64.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"117\" y\u003d\"-78.3\" font-family\u003d\"Times,serif\" font-size\u003d\"14.00\"\u003elabel 2\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n1\u0026#45;\u0026gt;n2 --\u003e\n\u003cg id\u003d\"edge1\" class\u003d\"edge\"\u003e\u003ctitle\u003en1\u0026#45;\u0026gt;n2\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"black\" d\u003d\"M52.9819,-36.6686C62.2713,-43.4246 72.9611,-51.199 82.867,-58.4033\"/\u003e\n\u003cpolygon fill\u003d\"black\" stroke\u003d\"black\" points\u003d\"80.8097,-61.2348 90.9557,-64.2859 84.9269,-55.5736 80.8097,-61.2348\"/\u003e\n\u003c/g\u003e\n\u003c!-- n3 --\u003e\n\u003cg id\u003d\"node3\" class\u003d\"node\"\u003e\u003ctitle\u003en3\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"black\" points\u003d\"180,-0.5 180,-36.5 234,-36.5 234,-0.5 180,-0.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"207\" y\u003d\"-14.3\" font-family\u003d\"Times,serif\" font-size\u003d\"14.00\"\u003elabel 3\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n1\u0026#45;\u0026gt;n3 --\u003e\n\u003cg id\u003d\"edge3\" class\u003d\"edge\"\u003e\u003ctitle\u003en1\u0026#45;\u0026gt;n3\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"black\" d\u003d\"M54.2645,-18.5C84.8509,-18.5 135.551,-18.5 169.843,-18.5\"/\u003e\n\u003cpolygon fill\u003d\"black\" stroke\u003d\"black\" points\u003d\"169.918,-22.0001 179.918,-18.5 169.918,-15.0001 169.918,-22.0001\"/\u003e\n\u003c/g\u003e\n\u003c!-- n2\u0026#45;\u0026gt;n3 --\u003e\n\u003cg id\u003d\"edge2\" class\u003d\"edge\"\u003e\u003ctitle\u003en2\u0026#45;\u0026gt;n3\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"black\" d\u003d\"M142.982,-64.3314C152.271,-57.5754 162.961,-49.801 172.867,-42.5967\"/\u003e\n\u003cpolygon fill\u003d\"black\" stroke\u003d\"black\" points\u003d\"174.927,-45.4264 180.956,-36.7141 170.81,-39.7652 174.927,-45.4264\"/\u003e\n\u003c/g\u003e\n\u003c/g\u003e\n\u003c/svg\u003e\n",
        "stylesByNodeId": {
            "n2": [
                "a"
            ]
        },
        "id": "dag12"
    },
    "colors": {
        "a": {
            "line": "#444",
            "fill": "#fff",
            "text": "#888",
            "textInverse": "#888"
        },
        "b": {
            "line": "#AA8E39",
            "fill": "#FFEAAA",
            "text": "#806515",
            "textInverse": "#AA8E39"
        },
        "c": {
            "line": "#306E12",
            "fill": "#519331",
            "text": "#ABDD93",
            "textInverse": "#306E12"
        }
    },
    "idsToHighlight": []
}

class DiagramSlidesDemo extends Component {
    render() {
        return <div>
            <GraphVizSvg {...testData}/></div>
    }
}

export default DiagramSlidesDemo