/*
 * Copyright 2021 znai maintainers
 * Copyright 2019 TWO SIGMA OPEN SOURCE, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from "react";
import GraphVizSvg from "./GraphVizSvg";

import diagramWithShapes from "./DiagramTestData";
import { stubGraphvizGlobalAssets } from "./graphvizTestGlobalAssets";

export function graphVizSvgDemo(registry) {
  stubGraphvizGlobalAssets();

  registry
    .add("todo", () => <GraphVizSvg {...todo()} />)
    .add("with cluster and dots", () => <GraphVizSvg {...createDiagramWithDotsAndSubGraphs("id8")} />)
    .add("default colors", () => <GraphVizSvg {...createDiagramWithoutColors("id1")} />)
    .add("multiple colors", () => <GraphVizSvg {...createDiagramWithColors("id1")} />)
    .add("shapes", () => <GraphVizSvg {...createDiagramWithShapes()} />)
    .add("from ellipses", () => <GraphVizSvg {...diagramFromEllipses()} />);
}

function todo() {
  return {
    "diagram" : {
      "isInvertedTextColorByStyleId" : { },
      "svg" : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<!-- Generated by graphviz version 11.0.0 (20240428.1522)\n -->\n<!-- Pages: 1 -->\n<svg width=\"134pt\" height=\"188pt\"\n viewBox=\"0.00 0.00 134.00 188.00\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n<g id=\"page0,1_graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 184)\">\n<polygon fill=\"white\" stroke=\"none\" points=\"-4,4 -4,-184 130,-184 130,4 -4,4\"/>\n<!-- a -->\n<g id=\"node1\" class=\"node\">\n<title>a</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"27\" cy=\"-162\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"27\" y=\"-156.95\" font-family=\"Times,serif\" font-size=\"14.00\">a</text>\n</g>\n<!-- b -->\n<g id=\"node2\" class=\"node\">\n<title>b</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"63\" cy=\"-90\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"63\" y=\"-84.95\" font-family=\"Times,serif\" font-size=\"14.00\">b</text>\n</g>\n<!-- a&#45;&gt;b -->\n<g id=\"edge1\" class=\"edge\">\n<title>a&#45;&gt;b</title>\n<path fill=\"none\" stroke=\"black\" d=\"M35.35,-144.76C39.58,-136.55 44.81,-126.37 49.58,-117.09\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"52.54,-118.99 54,-108.49 46.32,-115.79 52.54,-118.99\"/>\n</g>\n<!-- c -->\n<g id=\"node3\" class=\"node\">\n<title>c</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"27\" cy=\"-18\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"27\" y=\"-12.95\" font-family=\"Times,serif\" font-size=\"14.00\">c</text>\n</g>\n<!-- b&#45;&gt;c -->\n<g id=\"edge2\" class=\"edge\">\n<title>b&#45;&gt;c</title>\n<path fill=\"none\" stroke=\"black\" d=\"M54.65,-72.76C50.42,-64.55 45.19,-54.37 40.42,-45.09\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"43.68,-43.79 36,-36.49 37.46,-46.99 43.68,-43.79\"/>\n</g>\n<!-- e -->\n<g id=\"node5\" class=\"node\">\n<title>e</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"99\" cy=\"-18\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"99\" y=\"-12.95\" font-family=\"Times,serif\" font-size=\"14.00\">e</text>\n</g>\n<!-- b&#45;&gt;e -->\n<g id=\"edge4\" class=\"edge\">\n<title>b&#45;&gt;e</title>\n<path fill=\"none\" stroke=\"black\" d=\"M71.35,-72.76C75.58,-64.55 80.81,-54.37 85.58,-45.09\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"88.54,-46.99 90,-36.49 82.32,-43.79 88.54,-46.99\"/>\n</g>\n<!-- d -->\n<g id=\"node4\" class=\"node\">\n<title>d</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"99\" cy=\"-162\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"99\" y=\"-156.95\" font-family=\"Times,serif\" font-size=\"14.00\">d</text>\n</g>\n<!-- d&#45;&gt;b -->\n<g id=\"edge3\" class=\"edge\">\n<title>d&#45;&gt;b</title>\n<path fill=\"none\" stroke=\"black\" d=\"M90.65,-144.76C86.42,-136.55 81.19,-126.37 76.42,-117.09\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"79.68,-115.79 72,-108.49 73.46,-118.99 79.68,-115.79\"/>\n</g>\n</g>\n</svg>\n",
      "stylesByNodeId" : { },
      "id" : "gv_4d7301fa_262b_4436_91d1_930c3cbb084b"
    },
    "urls" : [ ],
    "type" : "GraphVizDiagram"
  }
}

function createDiagramWithDotsAndSubGraphs(id) {
  return {
    "diagram": {
      "shapeSvgByStyleId": {},
      "isInvertedTextColorByStyleId": {},
      "svg" : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<!-- Generated by graphviz version 11.0.0 (20240428.1522)\n -->\n<!-- Pages: 1 -->\n<svg width=\"152pt\" height=\"156pt\"\n viewBox=\"0.00 0.00 152.20 156.00\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n<g id=\"page0,1_graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 152)\">\n<polygon fill=\"white\" stroke=\"none\" points=\"-4,4 -4,-152 148.2,-152 148.2,4 -4,4\"/>\n<g id=\"clust1\" class=\"cluster\">\n<title>cluster_a</title>\n<path fill=\"none\" stroke=\"black\" d=\"M12,-8C12,-8 47.6,-8 47.6,-8 53.6,-8 59.6,-14 59.6,-20 59.6,-20 59.6,-106 59.6,-106 59.6,-112 53.6,-118 47.6,-118 47.6,-118 12,-118 12,-118 6,-118 0,-112 0,-106 0,-106 0,-20 0,-20 0,-14 6,-8 12,-8\"/>\n<text text-anchor=\"middle\" x=\"29.8\" y=\"-100.7\" font-family=\"Times,serif\" font-size=\"14.00\">old type</text>\n</g>\n<g id=\"clust2\" class=\"cluster\">\n<title>cluster_b</title>\n<path fill=\"none\" stroke=\"black\" d=\"M91.6,-8C91.6,-8 132.2,-8 132.2,-8 138.2,-8 144.2,-14 144.2,-20 144.2,-20 144.2,-128 144.2,-128 144.2,-134 138.2,-140 132.2,-140 132.2,-140 91.6,-140 91.6,-140 85.6,-140 79.6,-134 79.6,-128 79.6,-128 79.6,-20 79.6,-20 79.6,-14 85.6,-8 91.6,-8\"/>\n<text text-anchor=\"middle\" x=\"111.9\" y=\"-122.7\" font-family=\"Times,serif\" font-size=\"14.00\">new type</text>\n</g>\n<!-- a -->\n<g id=\"node1\" class=\"node\">\n<title>a</title>\n<ellipse fill=\"black\" stroke=\"black\" cx=\"29.8\" cy=\"-18\" rx=\"1.8\" ry=\"1.8\"/>\n</g>\n<!-- e -->\n<g id=\"node5\" class=\"node\">\n<title>e</title>\n<ellipse fill=\"black\" stroke=\"black\" cx=\"111.4\" cy=\"-18\" rx=\"1.8\" ry=\"1.8\"/>\n</g>\n<!-- a&#45;&gt;e -->\n<g id=\"edge1\" class=\"edge\">\n<title>a&#45;&gt;e</title>\n<path fill=\"none\" stroke=\"blue\" stroke-width=\"2\" d=\"M44.87,-18C59.35,-18 81.77,-18 96.27,-18\"/>\n<polygon fill=\"blue\" stroke=\"blue\" stroke-width=\"2\" points=\"44.95,-14.5 34.95,-18 44.95,-21.5 44.95,-14.5\"/>\n<polygon fill=\"blue\" stroke=\"blue\" stroke-width=\"2\" points=\"96.17,-21.5 106.17,-18 96.17,-14.5 96.17,-21.5\"/>\n</g>\n<!-- g -->\n<g id=\"node7\" class=\"node\">\n<title>g</title>\n<ellipse fill=\"black\" stroke=\"black\" cx=\"111.4\" cy=\"-40\" rx=\"1.8\" ry=\"1.8\"/>\n</g>\n<!-- a&#45;&gt;g -->\n<g id=\"edge2\" class=\"edge\">\n<title>a&#45;&gt;g</title>\n<path fill=\"none\" stroke=\"blue\" stroke-width=\"2\" d=\"M31.93,-18.31C38.86,-20.23 76.15,-30.54 96.74,-36.22\"/>\n<polygon fill=\"blue\" stroke=\"blue\" stroke-width=\"2\" points=\"95.71,-39.57 106.28,-38.86 97.58,-32.82 95.71,-39.57\"/>\n</g>\n<!-- b -->\n<g id=\"node2\" class=\"node\">\n<title>b</title>\n<ellipse fill=\"black\" stroke=\"black\" cx=\"29.8\" cy=\"-40\" rx=\"1.8\" ry=\"1.8\"/>\n</g>\n<!-- f -->\n<g id=\"node6\" class=\"node\">\n<title>f</title>\n<ellipse fill=\"black\" stroke=\"black\" cx=\"111.4\" cy=\"-62\" rx=\"1.8\" ry=\"1.8\"/>\n</g>\n<!-- b&#45;&gt;f -->\n<g id=\"edge3\" class=\"edge\">\n<title>b&#45;&gt;f</title>\n<path fill=\"none\" stroke=\"blue\" stroke-width=\"2\" d=\"M44.25,-43.72C58.96,-47.78 82.39,-54.26 97.05,-58.31\"/>\n<polygon fill=\"blue\" stroke=\"blue\" stroke-width=\"2\" points=\"45.41,-40.41 34.84,-41.12 43.55,-47.15 45.41,-40.41\"/>\n<polygon fill=\"blue\" stroke=\"blue\" stroke-width=\"2\" points=\"95.71,-61.57 106.28,-60.86 97.58,-54.82 95.71,-61.57\"/>\n</g>\n<!-- c -->\n<g id=\"node3\" class=\"node\">\n<title>c</title>\n<ellipse fill=\"black\" stroke=\"black\" cx=\"29.8\" cy=\"-62\" rx=\"1.8\" ry=\"1.8\"/>\n</g>\n<!-- c&#45;&gt;f -->\n<g id=\"edge5\" class=\"edge\">\n<title>c&#45;&gt;f</title>\n<path fill=\"none\" stroke=\"blue\" stroke-width=\"2\" d=\"M31.93,-62C38.82,-62 75.78,-62 96.42,-62\"/>\n<polygon fill=\"blue\" stroke=\"blue\" stroke-width=\"2\" points=\"96.17,-65.5 106.17,-62 96.17,-58.5 96.17,-65.5\"/>\n</g>\n<!-- d -->\n<g id=\"node4\" class=\"node\">\n<title>d</title>\n<ellipse fill=\"black\" stroke=\"black\" cx=\"29.8\" cy=\"-84\" rx=\"1.8\" ry=\"1.8\"/>\n</g>\n<!-- h -->\n<g id=\"node8\" class=\"node\">\n<title>h</title>\n<ellipse fill=\"black\" stroke=\"black\" cx=\"111.4\" cy=\"-84\" rx=\"1.8\" ry=\"1.8\"/>\n</g>\n<!-- d&#45;&gt;h -->\n<g id=\"edge4\" class=\"edge\">\n<title>d&#45;&gt;h</title>\n<path fill=\"none\" stroke=\"blue\" stroke-width=\"2\" d=\"M31.93,-84C38.82,-84 75.78,-84 96.42,-84\"/>\n<polygon fill=\"blue\" stroke=\"blue\" stroke-width=\"2\" points=\"96.17,-87.5 106.17,-84 96.17,-80.5 96.17,-87.5\"/>\n</g>\n<!-- i -->\n<g id=\"node9\" class=\"node\">\n<title>i</title>\n<ellipse fill=\"black\" stroke=\"black\" cx=\"111.4\" cy=\"-106\" rx=\"1.8\" ry=\"1.8\"/>\n</g>\n</g>\n</svg>\n",
      "stylesByNodeId": {
      },
      "id": id
    },
    "urls": {
    },
    "idsToHighlight": [],
    "wide": false,
    "type": "GraphVizDiagram"
  };
}

function createDiagramWithoutColors(id) {
  return {
    "diagram": {
      "shapeSvgByStyleId": {},
      "isInvertedTextColorByStyleId": {},
      "svg": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"UTF-8\" standalone\u003d\"no\"?\u003e\n\u003c!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"\u003e\n\u003c!-- Generated by graphviz version 2.40.1 (20161225.0304)\n --\u003e\n\u003c!-- Title: Generated Pages: 1 --\u003e\n\u003csvg width\u003d\"275pt\" height\u003d\"197pt\"\n viewBox\u003d\"0.00 0.00 275.32 197.00\" xmlns\u003d\"http://www.w3.org/2000/svg\" xmlns:xlink\u003d\"http://www.w3.org/1999/xlink\"\u003e\n\u003cg id\u003d\"page0,1_graph0\" class\u003d\"graph\" transform\u003d\"scale(1 1) rotate(0) translate(4 193)\"\u003e\n\u003ctitle\u003eGenerated\u003c/title\u003e\n\u003cpolygon fill\u003d\"#ffffff00\" stroke\u003d\"transparent\" points\u003d\"-4,4 -4,-193 271.3198,-193 271.3198,4 -4,4\"/\u003e\n\u003c!-- n1 --\u003e\n\u003cg id\u003d\"node1\" class\u003d\"node\"\u003e\n\u003ctitle\u003en1\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"53.0591,-150.5 53.0591,-188.5 122.2065,-188.5 122.2065,-150.5 53.0591,-150.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"87.6328\" y\u003d\"-166.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003einput one\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n3 --\u003e\n\u003cg id\u003d\"node3\" class\u003d\"node\"\u003e\n\u003ctitle\u003en3\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"94.6797,-75.5 94.6797,-113.5 166.5859,-113.5 166.5859,-75.5 94.6797,-75.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"130.6328\" y\u003d\"-91.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003eprocessor\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n1\u0026#45;\u0026gt;n3 --\u003e\n\u003cg id\u003d\"edge1\" class\u003d\"edge\"\u003e\n\u003ctitle\u003en1\u0026#45;\u0026gt;n3\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"#000000\" d\u003d\"M98.7064,-150.1856C103.5214,-141.7873 109.2571,-131.7833 114.5297,-122.5868\"/\u003e\n\u003cpolygon fill\u003d\"#000000\" stroke\u003d\"#000000\" points\u003d\"117.6592,-124.1651 119.5968,-113.7489 111.5865,-120.6834 117.6592,-124.1651\"/\u003e\n\u003c/g\u003e\n\u003c!-- n2 --\u003e\n\u003cg id\u003d\"node2\" class\u003d\"node\"\u003e\n\u003ctitle\u003en2\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"140.6206,-150.5 140.6206,-188.5 208.645,-188.5 208.645,-150.5 140.6206,-150.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"174.6328\" y\u003d\"-166.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003einput two\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n2\u0026#45;\u0026gt;n3 --\u003e\n\u003cg id\u003d\"edge2\" class\u003d\"edge\"\u003e\n\u003ctitle\u003en2\u0026#45;\u0026gt;n3\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"#000000\" d\u003d\"M163.3017,-150.1856C158.3747,-141.7873 152.5057,-131.7833 147.1104,-122.5868\"/\u003e\n\u003cpolygon fill\u003d\"#000000\" stroke\u003d\"#000000\" points\u003d\"150.0045,-120.6031 141.9255,-113.7489 143.9669,-124.1452 150.0045,-120.6031\"/\u003e\n\u003c/g\u003e\n\u003c!-- n4 --\u003e\n\u003cg id\u003d\"node4\" class\u003d\"node\"\u003e\n\u003ctitle\u003en4\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"0,-.5 0,-38.5 75.2656,-38.5 75.2656,-.5 0,-.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"37.6328\" y\u003d\"-16.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003eoutput one\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n3\u0026#45;\u0026gt;n4 --\u003e\n\u003cg id\u003d\"edge3\" class\u003d\"edge\"\u003e\n\u003ctitle\u003en3\u0026#45;\u0026gt;n4\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"#000000\" d\u003d\"M106.683,-75.1856C95.4012,-66.0874 81.7828,-55.1048 69.6322,-45.3059\"/\u003e\n\u003cpolygon fill\u003d\"#000000\" stroke\u003d\"#000000\" points\u003d\"71.4828,-42.302 61.5015,-38.7489 67.0885,-47.7509 71.4828,-42.302\"/\u003e\n\u003c/g\u003e\n\u003c!-- n5 --\u003e\n\u003cg id\u003d\"node5\" class\u003d\"node\"\u003e\n\u003ctitle\u003en5\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"93.5615,-.5 93.5615,-38.5 167.7041,-38.5 167.7041,-.5 93.5615,-.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"130.6328\" y\u003d\"-16.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003eoutput two\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n3\u0026#45;\u0026gt;n5 --\u003e\n\u003cg id\u003d\"edge4\" class\u003d\"edge\"\u003e\n\u003ctitle\u003en3\u0026#45;\u0026gt;n5\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"#000000\" d\u003d\"M130.6328,-75.1856C130.6328,-67.2247 130.6328,-57.821 130.6328,-49.03\"/\u003e\n\u003cpolygon fill\u003d\"#000000\" stroke\u003d\"#000000\" points\u003d\"134.1329,-48.7489 130.6328,-38.7489 127.1329,-48.7489 134.1329,-48.7489\"/\u003e\n\u003c/g\u003e\n\u003c!-- n6 --\u003e\n\u003cg id\u003d\"node6\" class\u003d\"node\"\u003e\n\u003ctitle\u003en6\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"185.9458,-.5 185.9458,-38.5 267.3198,-38.5 267.3198,-.5 185.9458,-.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"226.6328\" y\u003d\"-16.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003eoutput three\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n3\u0026#45;\u0026gt;n6 --\u003e\n\u003cg id\u003d\"edge5\" class\u003d\"edge\"\u003e\n\u003ctitle\u003en3\u0026#45;\u0026gt;n6\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"#000000\" d\u003d\"M155.1061,-75.3803C166.9542,-66.1239 181.343,-54.8826 194.0999,-44.9163\"/\u003e\n\u003cpolygon fill\u003d\"#000000\" stroke\u003d\"#000000\" points\u003d\"196.4788,-47.4994 202.2043,-38.5848 192.1692,-41.9832 196.4788,-47.4994\"/\u003e\n\u003c/g\u003e\n\u003c/g\u003e\n\u003c/svg\u003e\n",
      "stylesByNodeId": {
      },
      "id": id
    },
    "idsToHighlight": [],
    "wide": false,
    "urls": {
      "n1": "http://link"
    },
    "type": "GraphVizDiagram"
  };
}

function createDiagramWithColors(id) {
  const withoutColors = createDiagramWithoutColors(id)
  withoutColors.diagram.stylesByNodeId = {
    n1: ["b"],
    n2: ["b"],
    n4: ["c"],
    n5: ["c"],
    n6: ["d"]
  }
  return withoutColors
}

function createDiagramWithShapes() {
  return {
    "diagram": diagramWithShapes,
    "idsToHighlight": [],
    "wide": false,
    "urls": {},
    "type": "GraphVizDiagram"
  };
}

function diagramFromEllipses() {
  return {
    "diagram": {
      "isInvertedTextColorByStyleId": {},
      "svg": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<!-- Generated by graphviz version 2.49.0 (20210828.1703)\n -->\n<!-- Pages: 1 -->\n<svg width=\"134pt\" height=\"188pt\"\n viewBox=\"0.00 0.00 134.00 188.00\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n<g id=\"graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 184)\">\n<polygon fill=\"white\" stroke=\"transparent\" points=\"-4,4 -4,-184 130,-184 130,4 -4,4\"/>\n<!-- a -->\n<g id=\"node1\" class=\"node\">\n<title>a</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"27\" cy=\"-162\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"27\" y=\"-158.3\" font-family=\"Times,serif\" font-size=\"14.00\">a</text>\n</g>\n<!-- b -->\n<g id=\"node2\" class=\"node\">\n<title>b</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"63\" cy=\"-90\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"63\" y=\"-86.3\" font-family=\"Times,serif\" font-size=\"14.00\">b</text>\n</g>\n<!-- a&#45;&gt;b -->\n<g id=\"edge1\" class=\"edge\">\n<title>a&#45;&gt;b</title>\n<path fill=\"none\" stroke=\"black\" d=\"M35.35,-144.76C39.71,-136.28 45.15,-125.71 50.04,-116.2\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"53.23,-117.64 54.7,-107.15 47.01,-114.44 53.23,-117.64\"/>\n</g>\n<!-- c -->\n<g id=\"node3\" class=\"node\">\n<title>c</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"27\" cy=\"-18\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"27\" y=\"-14.3\" font-family=\"Times,serif\" font-size=\"14.00\">c</text>\n</g>\n<!-- b&#45;&gt;c -->\n<g id=\"edge2\" class=\"edge\">\n<title>b&#45;&gt;c</title>\n<path fill=\"none\" stroke=\"black\" d=\"M54.65,-72.76C50.29,-64.28 44.85,-53.71 39.96,-44.2\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"42.99,-42.44 35.3,-35.15 36.77,-45.64 42.99,-42.44\"/>\n</g>\n<!-- e -->\n<g id=\"node5\" class=\"node\">\n<title>e</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"99\" cy=\"-18\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"99\" y=\"-14.3\" font-family=\"Times,serif\" font-size=\"14.00\">e</text>\n</g>\n<!-- b&#45;&gt;e -->\n<g id=\"edge4\" class=\"edge\">\n<title>b&#45;&gt;e</title>\n<path fill=\"none\" stroke=\"black\" d=\"M71.35,-72.76C75.71,-64.28 81.15,-53.71 86.04,-44.2\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"89.23,-45.64 90.7,-35.15 83.01,-42.44 89.23,-45.64\"/>\n</g>\n<!-- d -->\n<g id=\"node4\" class=\"node\">\n<title>d</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"99\" cy=\"-162\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"99\" y=\"-158.3\" font-family=\"Times,serif\" font-size=\"14.00\">d</text>\n</g>\n<!-- d&#45;&gt;b -->\n<g id=\"edge3\" class=\"edge\">\n<title>d&#45;&gt;b</title>\n<path fill=\"none\" stroke=\"black\" d=\"M90.65,-144.76C86.29,-136.28 80.85,-125.71 75.96,-116.2\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"78.99,-114.44 71.3,-107.15 72.77,-117.64 78.99,-114.44\"/>\n</g>\n</g>\n</svg>\n",
      "id": "gv_5bd98e8c_85ea_4d5b_919f_aaded08a1dae",
      "stylesByNodeId": {
        a: ["b"],
        b: ["b"],
        c: ["c"],
        e: ["a"],
        d: ["d"]
      }
    },
    "type": "GraphVizDiagram",
    "urls": {}
  };
}