/*
 * Copyright 2021 znai maintainers
 * Copyright 2019 TWO SIGMA OPEN SOURCE, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from "react";
import GraphVizSvg from "./GraphVizSvg";

import diagramWithShapes from "./DiagramTestData";
import { stubGraphvizGlobalAssets } from "./graphvizTestGlobalAssets";

export function graphVizSvgDemo(registry) {
  stubGraphvizGlobalAssets();

  registry
    .add("multiple colors", () => <GraphVizSvg {...createDiagramWithColors("id1")} />)
    .add("shapes", () => <GraphVizSvg {...createDiagramWithShapes()} />)
    .add("from ellipses", () => <GraphVizSvg {...diagramFromEllipses()} />);
}

function createDiagramWithColors(id) {
  return {
    "diagram": {
      "shapeSvgByStyleId": {},
      "isInvertedTextColorByStyleId": {},
      "svg": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"UTF-8\" standalone\u003d\"no\"?\u003e\n\u003c!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"\u003e\n\u003c!-- Generated by graphviz version 2.40.1 (20161225.0304)\n --\u003e\n\u003c!-- Title: Generated Pages: 1 --\u003e\n\u003csvg width\u003d\"275pt\" height\u003d\"197pt\"\n viewBox\u003d\"0.00 0.00 275.32 197.00\" xmlns\u003d\"http://www.w3.org/2000/svg\" xmlns:xlink\u003d\"http://www.w3.org/1999/xlink\"\u003e\n\u003cg id\u003d\"page0,1_graph0\" class\u003d\"graph\" transform\u003d\"scale(1 1) rotate(0) translate(4 193)\"\u003e\n\u003ctitle\u003eGenerated\u003c/title\u003e\n\u003cpolygon fill\u003d\"#ffffff00\" stroke\u003d\"transparent\" points\u003d\"-4,4 -4,-193 271.3198,-193 271.3198,4 -4,4\"/\u003e\n\u003c!-- n1 --\u003e\n\u003cg id\u003d\"node1\" class\u003d\"node\"\u003e\n\u003ctitle\u003en1\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"53.0591,-150.5 53.0591,-188.5 122.2065,-188.5 122.2065,-150.5 53.0591,-150.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"87.6328\" y\u003d\"-166.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003einput one\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n3 --\u003e\n\u003cg id\u003d\"node3\" class\u003d\"node\"\u003e\n\u003ctitle\u003en3\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"94.6797,-75.5 94.6797,-113.5 166.5859,-113.5 166.5859,-75.5 94.6797,-75.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"130.6328\" y\u003d\"-91.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003eprocessor\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n1\u0026#45;\u0026gt;n3 --\u003e\n\u003cg id\u003d\"edge1\" class\u003d\"edge\"\u003e\n\u003ctitle\u003en1\u0026#45;\u0026gt;n3\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"#000000\" d\u003d\"M98.7064,-150.1856C103.5214,-141.7873 109.2571,-131.7833 114.5297,-122.5868\"/\u003e\n\u003cpolygon fill\u003d\"#000000\" stroke\u003d\"#000000\" points\u003d\"117.6592,-124.1651 119.5968,-113.7489 111.5865,-120.6834 117.6592,-124.1651\"/\u003e\n\u003c/g\u003e\n\u003c!-- n2 --\u003e\n\u003cg id\u003d\"node2\" class\u003d\"node\"\u003e\n\u003ctitle\u003en2\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"140.6206,-150.5 140.6206,-188.5 208.645,-188.5 208.645,-150.5 140.6206,-150.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"174.6328\" y\u003d\"-166.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003einput two\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n2\u0026#45;\u0026gt;n3 --\u003e\n\u003cg id\u003d\"edge2\" class\u003d\"edge\"\u003e\n\u003ctitle\u003en2\u0026#45;\u0026gt;n3\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"#000000\" d\u003d\"M163.3017,-150.1856C158.3747,-141.7873 152.5057,-131.7833 147.1104,-122.5868\"/\u003e\n\u003cpolygon fill\u003d\"#000000\" stroke\u003d\"#000000\" points\u003d\"150.0045,-120.6031 141.9255,-113.7489 143.9669,-124.1452 150.0045,-120.6031\"/\u003e\n\u003c/g\u003e\n\u003c!-- n4 --\u003e\n\u003cg id\u003d\"node4\" class\u003d\"node\"\u003e\n\u003ctitle\u003en4\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"0,-.5 0,-38.5 75.2656,-38.5 75.2656,-.5 0,-.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"37.6328\" y\u003d\"-16.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003eoutput one\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n3\u0026#45;\u0026gt;n4 --\u003e\n\u003cg id\u003d\"edge3\" class\u003d\"edge\"\u003e\n\u003ctitle\u003en3\u0026#45;\u0026gt;n4\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"#000000\" d\u003d\"M106.683,-75.1856C95.4012,-66.0874 81.7828,-55.1048 69.6322,-45.3059\"/\u003e\n\u003cpolygon fill\u003d\"#000000\" stroke\u003d\"#000000\" points\u003d\"71.4828,-42.302 61.5015,-38.7489 67.0885,-47.7509 71.4828,-42.302\"/\u003e\n\u003c/g\u003e\n\u003c!-- n5 --\u003e\n\u003cg id\u003d\"node5\" class\u003d\"node\"\u003e\n\u003ctitle\u003en5\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"93.5615,-.5 93.5615,-38.5 167.7041,-38.5 167.7041,-.5 93.5615,-.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"130.6328\" y\u003d\"-16.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003eoutput two\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n3\u0026#45;\u0026gt;n5 --\u003e\n\u003cg id\u003d\"edge4\" class\u003d\"edge\"\u003e\n\u003ctitle\u003en3\u0026#45;\u0026gt;n5\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"#000000\" d\u003d\"M130.6328,-75.1856C130.6328,-67.2247 130.6328,-57.821 130.6328,-49.03\"/\u003e\n\u003cpolygon fill\u003d\"#000000\" stroke\u003d\"#000000\" points\u003d\"134.1329,-48.7489 130.6328,-38.7489 127.1329,-48.7489 134.1329,-48.7489\"/\u003e\n\u003c/g\u003e\n\u003c!-- n6 --\u003e\n\u003cg id\u003d\"node6\" class\u003d\"node\"\u003e\n\u003ctitle\u003en6\u003c/title\u003e\n\u003cpolygon fill\u003d\"none\" stroke\u003d\"#000000\" points\u003d\"185.9458,-.5 185.9458,-38.5 267.3198,-38.5 267.3198,-.5 185.9458,-.5\"/\u003e\n\u003ctext text-anchor\u003d\"middle\" x\u003d\"226.6328\" y\u003d\"-16.5\" font-family\u003d\"Helvetica,sans-Serif\" font-size\u003d\"10.00\" fill\u003d\"#000000\"\u003eoutput three\u003c/text\u003e\n\u003c/g\u003e\n\u003c!-- n3\u0026#45;\u0026gt;n6 --\u003e\n\u003cg id\u003d\"edge5\" class\u003d\"edge\"\u003e\n\u003ctitle\u003en3\u0026#45;\u0026gt;n6\u003c/title\u003e\n\u003cpath fill\u003d\"none\" stroke\u003d\"#000000\" d\u003d\"M155.1061,-75.3803C166.9542,-66.1239 181.343,-54.8826 194.0999,-44.9163\"/\u003e\n\u003cpolygon fill\u003d\"#000000\" stroke\u003d\"#000000\" points\u003d\"196.4788,-47.4994 202.2043,-38.5848 192.1692,-41.9832 196.4788,-47.4994\"/\u003e\n\u003c/g\u003e\n\u003c/g\u003e\n\u003c/svg\u003e\n",
      "stylesByNodeId": {
        n1: ["b"],
        n2: ["b"],
        n4: ["c"],
        n5: ["c"],
        n6: ["d"]
      },
      "id": id
    },
    "idsToHighlight": [],
    "wide": false,
    "urls": {
      "n1": "http://link"
    },
    "type": "GraphVizDiagram"
  };
}

function createDiagramWithShapes() {
  return {
    "diagram": diagramWithShapes,
    "idsToHighlight": [],
    "wide": false,
    "urls": {},
    "type": "GraphVizDiagram"
  };
}

function diagramFromEllipses() {
  return {
    "diagram": {
      "isInvertedTextColorByStyleId": {},
      "svg": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<!-- Generated by graphviz version 2.49.0 (20210828.1703)\n -->\n<!-- Pages: 1 -->\n<svg width=\"134pt\" height=\"188pt\"\n viewBox=\"0.00 0.00 134.00 188.00\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n<g id=\"graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 184)\">\n<polygon fill=\"white\" stroke=\"transparent\" points=\"-4,4 -4,-184 130,-184 130,4 -4,4\"/>\n<!-- a -->\n<g id=\"node1\" class=\"node\">\n<title>a</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"27\" cy=\"-162\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"27\" y=\"-158.3\" font-family=\"Times,serif\" font-size=\"14.00\">a</text>\n</g>\n<!-- b -->\n<g id=\"node2\" class=\"node\">\n<title>b</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"63\" cy=\"-90\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"63\" y=\"-86.3\" font-family=\"Times,serif\" font-size=\"14.00\">b</text>\n</g>\n<!-- a&#45;&gt;b -->\n<g id=\"edge1\" class=\"edge\">\n<title>a&#45;&gt;b</title>\n<path fill=\"none\" stroke=\"black\" d=\"M35.35,-144.76C39.71,-136.28 45.15,-125.71 50.04,-116.2\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"53.23,-117.64 54.7,-107.15 47.01,-114.44 53.23,-117.64\"/>\n</g>\n<!-- c -->\n<g id=\"node3\" class=\"node\">\n<title>c</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"27\" cy=\"-18\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"27\" y=\"-14.3\" font-family=\"Times,serif\" font-size=\"14.00\">c</text>\n</g>\n<!-- b&#45;&gt;c -->\n<g id=\"edge2\" class=\"edge\">\n<title>b&#45;&gt;c</title>\n<path fill=\"none\" stroke=\"black\" d=\"M54.65,-72.76C50.29,-64.28 44.85,-53.71 39.96,-44.2\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"42.99,-42.44 35.3,-35.15 36.77,-45.64 42.99,-42.44\"/>\n</g>\n<!-- e -->\n<g id=\"node5\" class=\"node\">\n<title>e</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"99\" cy=\"-18\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"99\" y=\"-14.3\" font-family=\"Times,serif\" font-size=\"14.00\">e</text>\n</g>\n<!-- b&#45;&gt;e -->\n<g id=\"edge4\" class=\"edge\">\n<title>b&#45;&gt;e</title>\n<path fill=\"none\" stroke=\"black\" d=\"M71.35,-72.76C75.71,-64.28 81.15,-53.71 86.04,-44.2\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"89.23,-45.64 90.7,-35.15 83.01,-42.44 89.23,-45.64\"/>\n</g>\n<!-- d -->\n<g id=\"node4\" class=\"node\">\n<title>d</title>\n<ellipse fill=\"none\" stroke=\"black\" cx=\"99\" cy=\"-162\" rx=\"27\" ry=\"18\"/>\n<text text-anchor=\"middle\" x=\"99\" y=\"-158.3\" font-family=\"Times,serif\" font-size=\"14.00\">d</text>\n</g>\n<!-- d&#45;&gt;b -->\n<g id=\"edge3\" class=\"edge\">\n<title>d&#45;&gt;b</title>\n<path fill=\"none\" stroke=\"black\" d=\"M90.65,-144.76C86.29,-136.28 80.85,-125.71 75.96,-116.2\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"78.99,-114.44 71.3,-107.15 72.77,-117.64 78.99,-114.44\"/>\n</g>\n</g>\n</svg>\n",
      "id": "gv_5bd98e8c_85ea_4d5b_919f_aaded08a1dae",
      "stylesByNodeId": {
        a: ["b"],
        b: ["b"],
        c: ["c"],
        e: ["a"],
        d: ["d"]
      }
    },
    "type": "GraphVizDiagram",
    "urls": {}
  };
}